# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-$(CONFIG_VIDEO_IPUV3) += mxc_ipuv3_fb.o ipu_common.o ipu_disp.o
obj-$(CONFIG_VIDEO_IMX8M_DCSS) += imx8m_dcss.o
obj-$(CONFIG_VIDEO_NWL_MIPI_DSI) += nwl-drv.o nwl-dsi.o
